<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <Import Project="../mrploch-development/dependencies/MicrosoftExtensions.Net9.Packages.props" />
  <Import Project="../mrploch-development/dependencies/Ploch.Packages.props" />
  <Import Project="../mrploch-development/dependencies/Common.Packages.props" />
  <Import Project="../mrploch-development/dependencies/Testing.Packages.props" />
  <Import Project="../mrploch-development/dependencies/Analyzers.Global.Packages.props" />
</Project>
